### ISSUE TITLE
qtemplate() not working with Github workflows

### ISSUE THREAD

**Issue by jhollway** [globalgov/qDatr#50]
because whisker reads workflow variables to be rendered?

**Comment by henriquesposito** [comment]
I have been trying to solve this issue for awhile now. So far I have not been successful. However I have thought about a (temporary) way around that could work. We can create workflow as a folder in the directory, load all the templates into it and, only then, try to move it to the .github folder. What do you think?

**Comment by jhollway** [comment]
An alternative is to find a way to attach multiple artefacts to the same release, obviating the need to name a zip folder.
