### ISSUE TITLE
Trim dependencies off of qPackage DESCRIPTION template

### ISSUE THREAD

**Issue by jhollway** [globalgov/qDatr#51]

**Comment by henriquesposito** [comment]
As of right now the description template for creating a package with qDatr imports 15 packages and suggests 4 more. In my opinion, for a data package in the ecosystem which will use qDatr for data collection, connection and correction, a lot of the dependencies we currently have seem unnecessary, at least for setting up a simple data package. I would suggest to keep dplyr, usethis, roxygen2 and lubridate for now as dependencies while, as suggestions, we can keep perhaps rlang, purrr and testthat in the template.

**Comment by jhollway** [comment]
Ok, implement and test.
