### ISSUE TITLE
Deprecate rearrange() in favour of dplyr::relocate()

### ISSUE THREAD

**Issue by jhollway** [globalgov/qDatr#55]
- [ ] https://stat.ethz.ch/R-manual/R-devel/library/base/html/Deprecated.html
- [ ] https://stat.ethz.ch/R-manual/R-devel/library/base/html/Defunct.html
- [ ] https://stackoverflow.com/questions/33304651/data-deprecation-in-r-package

**Comment by henriquesposito** [comment]
As of right now, when using the rearrange() function users will get a deprecated warning to use dplyr::relocate() instead; but function still works. This way we can make it defunct in the future. 

I can also make that the rearrange() function not work and users will simply get deprecated warning to use dplyr::relocate() instead, would that be better?
