### ISSUE TITLE
Suggest read_csv, read_dta etc for first line of preparation script based on file path passed to import

### ISSUE THREAD

**Issue by jhollway** [globalgov/qDatr#58]

**Comment by henriquesposito** [comment]
I am struggling to think of ways in which the template may suggest to proper way to load data according to format. There are three options I see here. First, a different message suggesting the proper way to import the file that could be generated according to file format. However, template would remain the same independent of format, simply a message suggesting type would be generated when running the import_data() for a specific file format. Second, we could upload different preparation templates for each format and, depending on the format of the data stored in the data-raw folder, a specific template is called. That is, call a different template depending on data format. Third, we could simply go briefly through all the options in the preparation template. This is more or less what we have it at the moment.
