### ISSUE TITLE
Error in export_data() function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qDatr#65]
When running the export_data() from qDatr, I get an error associated to the bzfile compression process. 

```r
qDatr::export_data(cow)
#Error in bzfile(file, "wb") : cannot open the connection
#In addition: Warning message:
#In bzfile(file, "wb") :
```

**Comment by henriquesposito** [comment]
I cannot seem to find much info on this error online. @jhollway Do you have any clues why the file does not compress correctly? Does it work correctly on your system? I have tried to change compression methods but the error remains. I can get the function to work without the compression call, but this means data is not compressed...

**Comment by jhollway** [comment]
Can you please add 'path' arguments and sensible defaults to all invocations of qtemplate? You may also want to move qtemplate to its own R script, since it's used across several functions now, not just import_/export_data

**Comment by henriquesposito** [comment]
I have solved the apparent compression issues by adding usethis::use_directory() to create a data folder. However, we now get path issues (as you rightly alluded to above). I understand we need to add a 'path' argument to the qtemplate() call now:

```
export_data(cow)
# Error in paste0(path, "/", save_as) : 
# argument "path" is missing, with no default 

```

Though, once I add a path argument (by alluding to a specific path with fs::path or creating a path vector as new_path <- fs::path), the error I get is:

```
export_data(cow)
# Error in file(path, open = file_mode, encoding = "utf-8") : 
#  cannot open the connection
# In addition: Warning message:
# In file(path, open = file_mode, encoding = "utf-8") 
```

@jhollway Do you have a clue of what I am doing wrong?

**Comment by henriquesposito** [comment]
This issue was fixed by adding a correct path call to the export_data() function.
